// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACCk5Kky8Ct4C_qWiehF1-TU6ap0UAYp0',
    appId: '1:952848614020:web:e37edc6a47fef5a933b8d1',
    messagingSenderId: '952848614020',
    projectId: 'estai-edb36',
    authDomain: 'estai-edb36.firebaseapp.com',
    storageBucket: 'estai-edb36.firebasestorage.app',
    measurementId: 'G-XD1W2XMK23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFIGK_PnOmv5wSB8vPaStPxuafw5oWCY',
    appId: '1:952848614020:android:ab0760fad12119c333b8d1',
    messagingSenderId: '952848614020',
    projectId: 'estai-edb36',
    storageBucket: 'estai-edb36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv35GDGSeNErQ2D0niIWx1CrJdNx9iKZk',
    appId: '1:952848614020:ios:cd0dae1d6e7570b933b8d1',
    messagingSenderId: '952848614020',
    projectId: 'estai-edb36',
    storageBucket: 'estai-edb36.firebasestorage.app',
    iosBundleId: 'com.example.estai',
  );
}
